---
- name: Deploy Web server
  hosts: all
  become: true
  become_method: su
  become_user: root

  tasks:

    - name: "Include var"
      include_vars:
        file: "vars.yml"

    - name: "Include role"
      include_role:
        name: "carlosbuenosvinos.ansistrano-deploy"
