---
- name: Install Web server
  hosts: all
  become: true
  become_method: su
  become_user: root

  tasks:
    
    - name: "Include var"
      include_vars:
        file: "vars.yml"

    - name: "Include roles in loop"
      include_role:
        name: "{{ item }}"
      with_items:
        - sys
        - user
        - security
        - server
        - tools

    - name: "SYS | Reboot server"
      shell: sleep 2 && shutdown -r now "Ansible reboot"
      async: 1
      poll: 0
      ignore_errors: true

    - name: "SYS | Wait for server to come back"
      local_action: wait_for
      args:
        host: "{{ inventory_hostname }}"
        port: 22
        state: started
        delay: 30
        timeout: 300
      become: false

